### ISSUE TITLE
mixed configuration files

### ISSUE THREAD

**Issue by mjaghouri** [AMCeScience/configuration-manager#1]
It looks like the configuration files are mixed up. 
The processing manager starts looking for the configuration file in the wrong place.
Luis had to duplicate everything in the two files to make it work.

**Comment by juanlufont** [comment]
I can confirm that:
/home/guse/processingmanager.config.json
/home/guse/guse/apache-tomcat-6.0.39/conf/config.json
/home/guse/guse/apache-tomcat-6.0.36/webapps/config.json

the last one is a symlink to the second one (processing manager should not use hard coded Tomcat paths.

**Comment by mjaghouri** [comment]
The path is hardcoded in Configuration Manager and not in the processing manager. 
To the attention of @Flythe

**Comment by Flythe** [comment]
I've got an idea for this we can also merge the processing manager config into the bigger config file. Lets discuss tomorrow.

**Comment by Flythe** [comment]
The configuration manager now traverses the folder tree searching for the config file. Please update to the latest version 1.0.12. You can now initialise the manager with: no parameters, path to the configuration file, path to the configuration file and a string used in logging, root folder from where search will start and name of configuration file and string used in logging. For each of the cases the manager will check if a file can be found through the input parameters. If not the search is triggered which is also stored in a cache to speed up multiple deployments in a short time (debugging).

EDIT: there are a few educated guesses, when no parameters are given for each of these: root from which search is started (/home), name of configuration file (config.json), default path where configuration file is located ({catalina.base}/conf/config.json).

**Comment by juanlufont** [comment]
Have you push the 1.0.12 to GitHub? I cannot see it :-/

**Comment by mjaghouri** [comment]
Allard
Is the config file of processing manager disentangled from the rest?
Luis had to duplicate the configurations into many files to get the portal
working.

**Comment by Flythe** [comment]
There are two config files now, one for processing one for the rest. Lets put processing in the main config as well to clean things up.

**Comment by mjaghouri** [comment]
That would mean that processing manager has no control on its config file.
I prefer to keep them separate because they belong to two different pieces
of software.
